name: windows

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
        ruby: [ '2.7', '2.6', 'mswin', 'mingw' ]
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set up Bundler
      run: gem install bundler --no-document
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: rake

